name: Publish
on:
  push:
    branches:
      - main
    paths:
      - src/jsr.json

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
